CREATE TABLE IF NOT EXISTS token
(
    token VARCHAR(50) PRIMARY KEY,
    type VARCHAR(10) NOT NULL,
    created_date TIMESTAMP WITH TIME ZONE
);

INSERT INTO token VALUES ('AK001', 'API_KEY', CURRENT_TIMESTAMP);
INSERT INTO token VALUES ('AK002', 'API_KEY', CURRENT_TIMESTAMP);
INSERT INTO token VALUES ('AK003', 'API_KEY', CURRENT_TIMESTAMP);
INSERT INTO token VALUES ('AK004', 'API_KEY', CURRENT_TIMESTAMP);
INSERT INTO token VALUES ('AK005', 'API_KEY', CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS token_access
(
    token VARCHAR(50) NOT NULL,
    accessed_date TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT token_accessed_Date PRIMARY KEY (token, accessed_date)
);
